version: '3.8'

services:
  wise-redis:
    image: redis:6.2
    container_name: wise-redis

  wise-mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: wise-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot
      - MYSQL_DATABASE=wise_database
      - MYSQL_USER=wiseuser
      - MYSQL_PASSWORD=wisepass
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './data:/var/lib/mysql'

  wise-api:
    image: wiseberkeley/wise-api-dev:latest
    container_name: wise-api
    expose:
      - '5005'
    depends_on:
      - wise-redis
      - wise-mysql
    ports:
      - '5005:5005'
      - '8080:8080'
    volumes:
      - '../WISE-API:/app'
    command: >
      bash -c '/app/create-application-dockerdev-properties-if-necessary.sh &&
      mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005" -Dspring-boot.run.profiles=dockerdev'

  wise-client:
    image: wiseberkeley/wise-client-dev:latest
    container_name: wise-client
    depends_on:
      - wise-api
    ports:
      - '4200:4200'
    volumes:
      - '../WISE-Client:/app'

  wise-nginx:
    image: nginx:1.22
    container_name: wise-nginx
    depends_on:
      - wise-client
    ports:
      - '81:80'
    volumes:
      - '${PWD}/nginx/conf.d:/etc/nginx/conf.d'
